/**
 * Cue sidecar file generation (Spec §15): "a sidecar file (e.g.
 * 1x01.cues.json) is auto-generated by parsing the plain-English
 * SFX:/MUSIC:/AMB: conventions already written naturally in the script — no
 * special syntax required from the writer, no change to how scripts are
 * authored." Regenerated from the script on every (re)index, never
 * hand-edited, safe to delete — the same files-as-truth-plus-rebuildable-
 * derived-data philosophy as the SQL index (Spec §2.2). No `vscode`
 * dependency, just `fs`, so it's callable directly from `index/build.ts`.
 */

import * as fsp from 'node:fs/promises';
import * as path from 'node:path';
import { extractCues, type CueEntry } from './parseCues';

const SCHEMA_VERSION = 1;

/** The cue sidecar's on-disk JSON shape. */
export interface CueSidecar {
  schema_version: number;
  /** The generating `.fountain` file's name, relative — for a human glancing at the file to see where it came from. */
  script: string;
  /** A landmine warning against hand-editing, embedded directly in the data (JSON has no comments). */
  generated_by: string;
  cues: CueEntry[];
}

/** Derive a script's sidecar path: same directory, `.fountain` swapped for `.cues.json`. */
export function cueSidecarPathFor(scriptPath: string): string {
  return scriptPath.replace(/\.fountain$/, '.cues.json');
}

/**
 * (Re)generate a script's cue sidecar from its current text. If the script
 * now has no cues, any existing sidecar is removed instead of being left
 * behind with an empty list.
 *
 * @param scriptPath - Absolute path to the `.fountain` script.
 * @param scriptText - The script's current, already-read text.
 */
export async function updateCueSidecar(scriptPath: string, scriptText: string): Promise<void> {
  const cues = extractCues(scriptText);
  const sidecarPath = cueSidecarPathFor(scriptPath);

  if (cues.length === 0) {
    await removeCueSidecar(scriptPath);
    return;
  }

  const sidecar: CueSidecar = {
    schema_version: SCHEMA_VERSION,
    script: path.basename(scriptPath),
    generated_by: 'LoreFountain — auto-generated from the script; do not edit by hand, it will be overwritten',
    cues,
  };
  await fsp.writeFile(sidecarPath, `${JSON.stringify(sidecar, null, 2)}\n`, 'utf8');
}

/** Remove a script's cue sidecar, if one exists. Safe to call when absent. */
export async function removeCueSidecar(scriptPath: string): Promise<void> {
  try {
    await fsp.unlink(cueSidecarPathFor(scriptPath));
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }
}
